Generify adaptors code. Cleanup.
sbtqa/datajack pull request #23
Opened 2018-08-26 10:17 UTC by clicman

Refactoring is done. Now you can review the code style.

2018-08-27 07:40 UTC, kosteman requested changes

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +import ru.sbtqa.tag.datajack.exceptions.*;
Чет мне не очень нравится вайлдкард-импорт, если только это не статик методы

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +        return key.matches("(.+\\[\\d+\\])");
Вынеси "(.+\\[\\d+\\])" в psf

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +     * @throws DataException
либо опиши либо удали из джавдока

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    protected abstract <T extends AbstractDataProvider> T createInstance(BasicDBObject basicObject, String collectionName, String way) throws DataException;
Как насчет сделать DataException DataRuntimeException и не писать его в сигнатуре каждого второго метода? Есть какая то необходимость быть ему не рантайм?

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private static final String NOT_INITIALIZED_EXCEPTION = "BasicDBObject is not initialized yet";
Есть ли возможность сделать это сообщение более понятным для пользователя?

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private TestDataProvider getSimple(String key) throws DataException {
Хочется чтобы getSimple был таким же простым как getComplex. Как насчет оставить 
AbstractDataProvider dataProvider = createInstance((BasicDBObject) result, this.collectionName, this.way);
dataProvider.applyGenerator(this.callback);
dataProvider.setRootObject(this.rootObject, rootObjValue);
а промежуточную добычу значений вынести в методы, может даже в статики в утилиты. Было бы очень наглядно.

2018-08-27 07:40 UTC, kosteman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +            String result = this.basicObject.getString(VALUE_TPL);
я бы тело этого кеча вынес бы в отдельный метод или еще сильнее его подробил

2018-08-27 07:40 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
> +     * @param dataFilePath   path to an Excel file
Приди к единому стилю форматирования джавадоков внутри проекта

2018-08-27 07:40 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
> +            pureObject.append("value", getLink(row));
VALUE_TPL у тебя теперь private. Зачем?

2018-08-27 07:40 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
>          File file = FileUtils.getFile(dataFilePath + ".xlsx");
создай DEFAULT_EXTENSION как JsonDataProvider

2018-08-27 07:40 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
> +    protected ExcelDataProvider createInstance(String collectionName) throws DataException {
throws DataException - лишнее

2018-08-27 07:40 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
> +    public ExcelDataProvider fromCollection(String collectionName) throws DataException {
throws DataException - лишнее

2018-08-27 07:40 UTC, kosteman commented on providers/json-provider/src/main/java/ru/sbtqa/tag/datajack/providers/json/JsonDataProvider.java
> +    @Override
как насчет inherit джавадоки?

2018-08-27 07:40 UTC, kosteman commented on providers/mongo-provider/src/main/java/ru/sbtqa/tag/datajack/providers/MongoDataProvider.java
> +        this.basicObject = (BasicDBObject) this.collection.findOne(new BasicDBObject("_id", new ObjectId(refId)));
напрашивается psfS для "_id"

2018-08-28 01:22 UTC, kosteman commented on providers/excel-provider/src/main/java/ru/sbtqa/tag/datajack/providers/ExcelDataProvider.java
> +            pureObject.append("value", getLink(row));
VALUE_TPL

2018-08-28 01:27 UTC, kosteman commented on providers/properties-provider/src/main/java/ru/sbtqa/tag/datajack/providers/properties/PropertiesDataProvider.java
> +    public TestDataProvider fromCollection(String collName) throws DataException {
@inheritDoc.
Проверь еще раз по проекту, это не единственное место

2018-08-29 18:31 UTC, clicman commented on providers/properties-provider/src/main/java/ru/sbtqa/tag/datajack/providers/properties/PropertiesDataProvider.java
> +    public TestDataProvider fromCollection(String collName) throws DataException {
done

2018-08-30 01:00 UTC, kosteman approved these changes

2018-08-30 04:08 UTC, PavelAlennikov commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +            result = new BasicDBObject(key, result);
тут чекаем на не BasicDBObject и оборачиваем в BasicDBObj, т.е всегд вернется именно он, но почему мы тогда по контракту возвращаем не его, а Object?

2018-08-30 04:17 UTC, PavelAlennikov requested changes

2018-08-30 04:17 UTC, PavelAlennikov commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private Object parseArray(BasicDBObject basicO, String key) throws DataException {
здесь тоже

2018-08-30 04:17 UTC, PavelAlennikov commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private boolean isReference(BasicDBObject basicDBObject) {
этот метод надо в BasicDBObject перенести

2018-08-30 04:17 UTC, PavelAlennikov commented on providers/json-provider/src/main/java/ru/sbtqa/tag/datajack/providers/json/JsonDataProvider.java
> +    private final String extension;
в чем смысл? у json файла разве может быть что-то помимо DEFAULT_EXTENSION?

2018-08-30 04:17 UTC, PavelAlennikov commented on providers/mongo-provider/src/main/java/ru/sbtqa/tag/datajack/providers/MongoDataProvider.java
empty line

2018-08-30 04:17 UTC, PavelAlennikov commented on providers/mongo-provider/src/test/java/ru/sbtqa/tag/datajack/providers/MongoDataTest.java
> +                fromCollection("DataBlocks", "57a94a160a279ec293f61665").get("Common");
че за болезнь с точками, надо пофиксить

2018-08-30 04:21 UTC, clicman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +            result = new BasicDBObject(key, result);
Потому что там может быть три варианта. BasicDBObject DbList и String

2018-08-30 04:33 UTC, clicman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private Object parseArray(BasicDBObject basicO, String key) throws DataException {
Здесь мы не знаем что вернется, и два раза не будем парсить

2018-08-30 04:33 UTC, clicman commented on datajack-api/src/main/java/ru/sbtqa/tag/datajack/providers/AbstractDataProvider.java
> +    private boolean isReference(BasicDBObject basicDBObject) {
Это не наш метод.

2018-08-30 04:33 UTC, clicman commented on providers/json-provider/src/main/java/ru/sbtqa/tag/datajack/providers/json/JsonDataProvider.java
> +    private final String extension;
Может. jsonp - например.

2018-08-30 06:02 UTC, PavelAlennikov requested changes

2018-08-30 06:02 UTC, PavelAlennikov commented on providers/json-provider/src/main/java/ru/sbtqa/tag/datajack/providers/json/JsonDataProvider.java
вот тут тоже осталось

2018-08-30 06:04 UTC, PavelAlennikov approved these changes

2018-08-30 06:07 UTC, merged